// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYpuDuMAn_d-zHwbbbb1q0CUGJMAyA4BQ',
    appId: '1:179045679991:web:999d4e2d42d4e3a7ad1772',
    messagingSenderId: '179045679991',
    projectId: 'localshop-61a6a',
    authDomain: 'localshop-61a6a.firebaseapp.com',
    storageBucket: 'localshop-61a6a.appspot.com',
    measurementId: 'G-MVSHLK1HBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4fE5aKVKckFqHzWuHC0fRrt-yQGprGlE',
    appId: '1:179045679991:android:76367785030e1c1ead1772',
    messagingSenderId: '179045679991',
    projectId: 'localshop-61a6a',
    storageBucket: 'localshop-61a6a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo-Zy2NPEHwgZ4JzhoKlEfF5I1XzOBYdY',
    appId: '1:179045679991:ios:8d4b8ed3dd5c1d2dad1772',
    messagingSenderId: '179045679991',
    projectId: 'localshop-61a6a',
    storageBucket: 'localshop-61a6a.appspot.com',
    iosBundleId: 'com.example.localproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo-Zy2NPEHwgZ4JzhoKlEfF5I1XzOBYdY',
    appId: '1:179045679991:ios:8d4b8ed3dd5c1d2dad1772',
    messagingSenderId: '179045679991',
    projectId: 'localshop-61a6a',
    storageBucket: 'localshop-61a6a.appspot.com',
    iosBundleId: 'com.example.localproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYpuDuMAn_d-zHwbbbb1q0CUGJMAyA4BQ',
    appId: '1:179045679991:web:56599e24759b5aebad1772',
    messagingSenderId: '179045679991',
    projectId: 'localshop-61a6a',
    authDomain: 'localshop-61a6a.firebaseapp.com',
    storageBucket: 'localshop-61a6a.appspot.com',
    measurementId: 'G-FYEPSXGMPP',
  );
}
